# LDHolyExpBottle
#  Плагин на уникальные бутыли с опытом
#  (Идея взята у HolyWorld, режима Лайт.)

# true - активировно
# false - выключено

# Команды:
#  /ldholybottle give - выдать бутылки (Право на использование команды: ld.admin)
#  /ldholybottle reload - перезагрузка конфига (Право на использование команды: ld.admin)

# Все бутыли к команде /ldholybottle give:
#  bottle_one - 15 ур.
#  bottle_two - 30 ур.
#  bottle_three - 50 ур.
messages:
  no_perm: '&#ff7000<!> &fНету прав!'
  no_player: '&#ff7000<!> &fИгрок &#ff7000{player} &fне найден.'
  give-bottle: '&#05fb00<!> &fУспешно!'
  no_bottle: '&#ff7000<!> &fБутылек не найден.'
  reload-config: '&#05fb00<!> &fУспешно!'

item_bottle_one:
  name: '&#05fb00&lБутылек с 15 ур. опыта &#05fb00&l(315)'
  lore:
    - ' &fВ пузырьке &#05fb00315 опыта (15 ур.)'
    - ' &fКиньте пузырек, чтобы получить опыт'
  value: 315 # Количество выдаваемого опыта
  click-exp:
    enable: true # Если активировано, игрок будет получать сообщение при клике
    message: '&#05fb00&l<!> &fВы успешно получили &#05fb00&l15 ур. опыта'

item_bottle_two:
  name: '&#ffc900&lБутылек с 30 ур. опыта &#ffc900&l(1395)'
  lore:
    - ' &fВ пузырьке &#ffc9001395 опыта (30 ур.)'
    - ' &fКиньте пузырек, чтобы получить опыт'
  value: 1395 # Количество выдаваемого опыта
  click-exp:
    enable: true # Если активировано, игрок будет получать сообщение при клике
    message: '&#05fb00&l<!> &fВы успешно получили &#05fb00&l30 ур. опыта'

item_bottle_three:
  name: '&#ff7000&lБутылек с 50 ур. опыта &#ff7000&l(5345)'
  lore:
    - ' &fВ пузырьке &#ff70005345 опыта (50 ур.)'
    - ' &fКиньте пузырек, чтобы получить опыт'
  value: 5345 # Количество выдаваемого опыта
  click-exp:
    enable: true # Если активировано, игрок будет получать сообщение при клике
    message: '&#05fb00&l<!> &fВы успешно получили &#05fb00&l50 ур. опыта'